/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shawa;

import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author jmsan
 */
public class Consumo_total extends javax.swing.JDialog {

    final private Database db;
    /**
     * Creates new form B
     */
    public Consumo_total(java.awt.Frame parent, Database db) {
        super(parent,true);
        initComponents();
        this.db = db;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("Verduras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Refrigerador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Bebidas");
        jButton4.setPreferredSize(new java.awt.Dimension(105, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Preparados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CT_ver cv = new CT_ver(new javax.swing.JFrame(), true);
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                cv.getjTextField1().setText(rs.getString("we"));
                rs.next();
                cv.getjTextField2().setText(rs.getString("we"));
                rs.next();
                cv.getjTextField6().setText(rs.getString("we"));
                rs.next();
                cv.getjTextField7().setText(rs.getString("we"));
                rs.next();
                cv.getjTextField8().setText(rs.getString("we"));
                rs.next();
                cv.getjTextField9().setText(rs.getString("we"));
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        cv.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CT_ref cr = new CT_ref(new javax.swing.JFrame(), true);
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                cr.getjTextField1().setText(rs.getString("we"));
                rs.next();
                cr.getjTextField2().setText(rs.getString("we"));
                rs.next();
                cr.getjTextField4().setText(rs.getString("we"));
                rs.next();
                cr.getjTextField6().setText(rs.getString("we"));
                rs.next();
                cr.getjTextField7().setText(rs.getString("we"));
                
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        cr.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CT_beb cb = new CT_beb(new javax.swing.JFrame(), true);
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                cb.getBeb1().setText(rs.getString("we"));
               rs.next();
                cb.getBeb2().setText(rs.getString("we"));
                rs.next();
                cb.getBeb3().setText(rs.getString("we"));
                rs.next();
                cb.getBeb4().setText(rs.getString("we"));
                rs.next();
                cb.getBeb5().setText(rs.getString("we"));
                rs.next();
                cb.getBeb6().setText(rs.getString("we"));
                rs.next();
                cb.getBeb7().setText(rs.getString("we"));
                rs.next();
                cb.getBeb8().setText(rs.getString("we"));
                rs.next();
                cb.getBeb9().setText(rs.getString("we"));
                rs.next();
                cb.getBeb10().setText(rs.getString("we"));
                rs.next();
                cb.getBeb11().setText(rs.getString("we"));
                rs.next();
                cb.getBeb12().setText(rs.getString("we"));
                rs.next();
                cb.getBeb13().setText(rs.getString("we"));
                rs.next();
                cb.getBeb14().setText(rs.getString("we"));
                rs.next();
                cb.getBeb15().setText(rs.getString("we"));
                rs.next();
                cb.getBeb16().setText(rs.getString("we"));
                
                
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        cb.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

       CT_pre cp = new CT_pre(new javax.swing.JFrame(), true);
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                cp.getPre1().setText(rs.getString("we"));
                rs.next();
                cp.getPre2().setText(rs.getString("we"));
                rs.next();
                cp.getPre3().setText(rs.getString("we"));
                rs.next();
                cp.getPre4().setText(rs.getString("we"));
                rs.next();
                cp.getPre5().setText(rs.getString("we"));
                rs.next();
                cp.getPre6().setText(rs.getString("we"));
                rs.next();
                cp.getPre7().setText(rs.getString("we"));
                rs.next();
                cp.getPre8().setText(rs.getString("we"));
                rs.next();
                cp.getPre9().setText(rs.getString("we"));
                rs.next();
                cp.getPre10().setText(rs.getString("we"));
                rs.next();
                cp.getPre11().setText(rs.getString("we"));
                
                
                
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        cp.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Database po;
        po = null;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consumo_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consumo_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consumo_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consumo_total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consumo_total dialog = new Consumo_total(new javax.swing.JFrame(), po );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
