/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shawa;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author jmsan
 */
public class Entradas extends javax.swing.JDialog {

    final private Database db;
    
    /**
     * Creates new form
     * @param parent
     * @param db
     * @param modal
     */
     public Entradas(java.awt.Frame parent, Database db) {
        super(parent, true);
        initComponents();
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bebidas = new javax.swing.JButton();
        Preparados = new javax.swing.JButton();
        Verduras = new javax.swing.JButton();
        Refrigerador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Bebidas.setText("Bebidas");
        Bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasActionPerformed(evt);
            }
        });

        Preparados.setText("Preparados");
        Preparados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreparadosActionPerformed(evt);
            }
        });

        Verduras.setText("Verduras");
        Verduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdurasActionPerformed(evt);
            }
        });

        Refrigerador.setText("Refrigerador");
        Refrigerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrigeradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Preparados))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Verduras)
                        .addGap(18, 18, 18)
                        .addComponent(Refrigerador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bebidas)
                    .addComponent(Preparados))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Verduras)
                    .addComponent(Refrigerador))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasActionPerformed
        // TODO add your handling code here:
        En_Bebi eb = new En_Bebi(new javax.swing.JFrame(), true);
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                //System.out.println(rs.getString("we"));
                eb.getB1().setText(rs.getString("we"));
                rs.next();
               // System.out.println(rs.getString("we"));
                eb.getB2().setText(rs.getString("we"));
                rs.next();
                eb.getB3().setText(rs.getString("we"));
                rs.next();
                eb.getB4().setText(rs.getString("we"));
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        eb.setVisible(true);
       
        
    }//GEN-LAST:event_BebidasActionPerformed

    private void PreparadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreparadosActionPerformed
        // TODO add your handling code here:
        
        En_Pre epr = new En_Pre(new javax.swing.JFrame(), true);
        
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                //System.out.println(rs.getString("we"));
                epr.getjTextField1().setText(rs.getString("we"));
                rs.next();
               // System.out.println(rs.getString("we"));
                epr.getjTextField2().setText(rs.getString("we"));
                rs.next();
                epr.getjTextField3().setText(rs.getString("we"));
                rs.next();
                epr.getjTextField4().setText(rs.getString("we"));
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        
        epr.setVisible(true);
        
    }//GEN-LAST:event_PreparadosActionPerformed

    private void VerdurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdurasActionPerformed
        // TODO add your handling code here:
        
        En_Ver ev = new En_Ver(new javax.swing.JFrame(), true);
        
         //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                //System.out.println(rs.getString("we"));
                ev.getjTextField1().setText(rs.getString("we"));
                rs.next();
               // System.out.println(rs.getString("we"));
                ev.getjTextField2().setText(rs.getString("we"));
                rs.next();
                ev.getjTextField3().setText(rs.getString("we"));
                rs.next();
                ev.getjTextField4().setText(rs.getString("we"));
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        
        ev.setVisible(true);
        
    }//GEN-LAST:event_VerdurasActionPerformed

    private void RefrigeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrigeradorActionPerformed
        // TODO add your handling code here:
        
        En_Ref er = new En_Ref(new javax.swing.JFrame(), true);
        
         //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                //System.out.println(rs.getString("we"));
                er.getjTextField1().setText(rs.getString("we"));
                rs.next();
               // System.out.println(rs.getString("we"));
                er.getjTextField2().setText(rs.getString("we"));
                rs.next();
                er.getjTextField3().setText(rs.getString("we"));
                rs.next();
                er.getjTextField4().setText(rs.getString("we"));
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        
        er.setVisible(true);
        
    }//GEN-LAST:event_RefrigeradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        Database po;
        po=null;
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Entradas dialog = new Entradas(new javax.swing.JFrame(),po);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bebidas;
    private javax.swing.JButton Preparados;
    private javax.swing.JButton Refrigerador;
    private javax.swing.JButton Verduras;
    // End of variables declaration//GEN-END:variables
}
