/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shawa;

/**
 *
 * @author jmsan
 */
public class Entradas extends javax.swing.JDialog {

    /**
     * Creates new form Entradas
     * @param parent
     * @param modal
     */
    public Entradas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bebidas = new javax.swing.JButton();
        Postres = new javax.swing.JButton();
        Preparados = new javax.swing.JButton();
        Verduras = new javax.swing.JButton();
        Refrigerador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Bebidas.setText("Bebidas");
        Bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasActionPerformed(evt);
            }
        });

        Postres.setText("Postres");
        Postres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostresActionPerformed(evt);
            }
        });

        Preparados.setText("Preparados");
        Preparados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreparadosActionPerformed(evt);
            }
        });

        Verduras.setText("Verduras");
        Verduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdurasActionPerformed(evt);
            }
        });

        Refrigerador.setText("Refrigerador");
        Refrigerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrigeradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Preparados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Postres))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Verduras))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Refrigerador)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bebidas)
                    .addComponent(Postres))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preparados)
                    .addComponent(Verduras))
                .addGap(26, 26, 26)
                .addComponent(Refrigerador)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasActionPerformed
        // TODO add your handling code here:
        
        En_Bebi eb = new En_Bebi(new javax.swing.JFrame(), true);
        eb.setVisible(true);
        
    }//GEN-LAST:event_BebidasActionPerformed

    private void PostresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostresActionPerformed
        // TODO add your handling code here:
        
        En_Pos ep = new En_Pos(new javax.swing.JFrame(), true);
        ep.setVisible(true);
        
    }//GEN-LAST:event_PostresActionPerformed

    private void PreparadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreparadosActionPerformed
        // TODO add your handling code here:
        
        En_Pre epr = new En_Pre(new javax.swing.JFrame(), true);
        epr.setVisible(true);
        
    }//GEN-LAST:event_PreparadosActionPerformed

    private void VerdurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdurasActionPerformed
        // TODO add your handling code here:
        
        En_Ver ev = new En_Ver(new javax.swing.JFrame(), true);
        ev.setVisible(true);
        
    }//GEN-LAST:event_VerdurasActionPerformed

    private void RefrigeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrigeradorActionPerformed
        // TODO add your handling code here:
        
        En_Ref er = new En_Ref(new javax.swing.JFrame(), true);
        er.setVisible(true);
        
    }//GEN-LAST:event_RefrigeradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Entradas dialog = new Entradas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bebidas;
    private javax.swing.JButton Postres;
    private javax.swing.JButton Preparados;
    private javax.swing.JButton Refrigerador;
    private javax.swing.JButton Verduras;
    // End of variables declaration//GEN-END:variables
}
