/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shawa;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author jmsan
 */
public class Primis extends javax.swing.JFrame {
    private final String USER = "JM";
    private final String PASS = "kiko10";
    final private Database db;
    
    /**
     * Creates new form
     */
    public Primis() {
        db = Database.getDatabase(USER, PASS);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Registros");

        jMenuItem2.setText("Nueva Entrada");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Nuevo Registro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");

        jMenuItem1.setText("Modificar Inventario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setText("Mostrar Inventario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consumo Total");

        jMenuItem5.setText("Consumo Total");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

         new Entradas(this, db).setVisible(true);


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

       new Consumo_total(this, db).setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        new D(this, db).setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:\

        new E(this, db).setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        new E (this, db).setVisible(true);
        
        E e = new E(new javax.swing.JFrame(), true);
        //Primis p = new Primis();
        final String sql = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs = db.query(sql);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs.next();
                e.getBeb1().setText(rs.getString("we"));
               rs.next();
                e.getBeb2().setText(rs.getString("we"));
                rs.next();
                e.getBeb3().setText(rs.getString("we"));
                rs.next();
                e.getBeb4().setText(rs.getString("we"));
                rs.next();
                e.getBeb5().setText(rs.getString("we"));
                rs.next();
                e.getBeb6().setText(rs.getString("we"));
                rs.next();
                e.getBeb7().setText(rs.getString("we"));
                rs.next();
                e.getBeb8().setText(rs.getString("we"));
                rs.next();
                e.getBeb9().setText(rs.getString("we"));
                rs.next();
                e.getBeb10().setText(rs.getString("we"));
                rs.next();
                e.getBeb11().setText(rs.getString("we"));
                rs.next();
                e.getBeb12().setText(rs.getString("we"));
                rs.next();
                e.getBeb13().setText(rs.getString("we"));
                rs.next();
                e.getBeb14().setText(rs.getString("we"));
                rs.next();
                e.getBeb15().setText(rs.getString("we"));
                rs.next();
                e.getBeb16().setText(rs.getString("we"));
                
                
            
            // System.out.println(contador);
        rs.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
       
    //-----------------------------------------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------
        
        //Primis p = new Primis();
        final String sql2 = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs2 = db.query(sql2);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs2.next();
                e.getPre1().setText(rs2.getString("we"));
                rs2.next();
                e.getPre2().setText(rs2.getString("we"));
                rs2.next();
                e.getPre3().setText(rs2.getString("we"));
                rs2.next();
                e.getPre4().setText(rs2.getString("we"));
                rs2.next();
                e.getPre5().setText(rs2.getString("we"));
                rs2.next();
                e.getPre6().setText(rs2.getString("we"));
                rs2.next();
                e.getPre7().setText(rs2.getString("we"));
                rs2.next();
                e.getPre8().setText(rs2.getString("we"));
                rs2.next();
                e.getPre9().setText(rs2.getString("we"));
                rs2.next();
                e.getPre10().setText(rs2.getString("we"));
                rs2.next();
                e.getPre11().setText(rs2.getString("we"));
                
                
                
            
            // System.out.println(contador);
        rs2.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        
    //-------------------------------------------------------------------------
    //-------------------------------------------------------------------------
    
        
        //Primis p = new Primis();
        final String sql3 = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs3 = db.query(sql3);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs3.next();
                e.getjTextField1().setText(rs3.getString("we"));
                rs3.next();
                e.getjTextField2().setText(rs3.getString("we"));
                rs3.next();
                e.getjTextField6().setText(rs3.getString("we"));
                rs3.next();
                e.getjTextField7().setText(rs3.getString("we"));
                rs3.next();
                e.getjTextField8().setText(rs3.getString("we"));
                rs3.next();
                e.getjTextField9().setText(rs3.getString("we"));
            
            // System.out.println(contador);
        rs3.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    
        
        //Primis p = new Primis();
        final String sql4 = "SELECT bebidas_id AS we, proveedor_id AS we2, nombre_bebida AS we3, other_details as we4"
                + " FROM bebidas";
        //System.out.println(sql);
        
        
        
        try {
             //int contador=0;
            ResultSet rs4 = db.query(sql4);
           
           //  System.out.println(contador);
           
             //   contador ++;
                rs4.next();
                e.getRef1().setText(rs4.getString("we"));
                rs4.next();
                e.getRef2().setText(rs4.getString("we"));
                rs4.next();
                e.getRef3().setText(rs4.getString("we"));
                rs4.next();
                e.getRef4().setText(rs4.getString("we"));
                rs4.next();
                e.getRef5().setText(rs4.getString("we"));
                
            
            // System.out.println(contador);
        rs4.first();
        } catch (SQLException ex) {
             System.out.println("error");
        }
        e.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Primis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Primis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Primis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Primis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Primis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
